QUEUE_RUN_PIPE: "task-tower_run_pipe"
QUEUE_Task_SUCCEED: "task-tower_succeed_Task"
QUEUE_Task_FAILED: "task-tower_failed_Task"
QUEUE_Task_FINISHED: "task-tower_finished_Task"
QUEUE_HOST: "localhost"
QUEUE_VHOST: "/task-tower"
QUEUE_USER: "task-tower"
QUEUE_PASSWORD: "RNeP2RpNDyY3s"
QUEUE_PORT: "5672"
TMP_FOLDER: "./temp"
DB_HOST: "localhost"
DB_USER: "task-toweruser"
DB_PASSWORD: "j37w47TbG0je5HI"
DB_PORT: "5432"
DB_NAME: "task-tower"