QUEUE_RUN_PIPE: "task-tower_run_pipe"
QUEUE_STAGE_SUCCEED: "task-tower_succeed_stage"
QUEUE_STAGE_FAILED: "task-tower_failed_stage"
QUEUE_STAGE_FINISHED: "task-tower_finished_stage"
QUEUE_HOST: "rabbitmq-task-tower"
QUEUE_VHOST: "/task-tower"
QUEUE_USER: "task-tower"
QUEUE_PASSWORD: "RNeP2RpNDyY3s"
QUEUE_PORT: "5672"
TMP_FOLDER: "/dashboard/appuser/temp"
DB_HOST: "postgres-task-tower"
DB_USER: "task-toweruser"
DB_PASSWORD: "j37w47TbG0je5HI"
DB_PORT: "5432"
DB_NAME: "task-tower"