QUEUE_RUN_PIPE: "dwas_run_pipe"
QUEUE_STAGE_SUCCEED: "dwas_succeed_stage"
QUEUE_STAGE_FAILED: "dwas_failed_stage"
QUEUE_STAGE_FINISHED: "dwas_finished_stage"
QUEUE_HOST: "rabbitmq-dwas"
QUEUE_VHOST: "/dwas"
QUEUE_USER: "dwas"
QUEUE_PASSWORD: "RNeP2RpNDyY3s"
QUEUE_PORT: "5672"
TMP_FOLDER: "/home/appuser/temp"
DB_HOST: "postgres-dwas"
DB_USER: "dwasuser"
DB_PASSWORD: "j37w47TbG0je5HI"
DB_PORT: "5432"
DB_NAME: "dwas"